# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

name: Integration tests

on:
  pull_request:
  schedule:
  - cron: "0 15 * * SAT"

permissions:
  contents: read
  packages: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  integration-test:
    uses: canonical/charm-ci/.github/workflows/integration-test.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
      actions: read
  allure-report:
    if: ${{ !cancelled() && github.event_name == 'schedule' }}
    needs:
    - integration-test
    uses: canonical/operator-workflows/.github/workflows/allure_report.yaml@main
