# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

name: Publish to edge

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish-to-edge:
    uses: canonical/charm-ci/.github/workflows/publish-artifacts.yml@58ae6614a3b143d4e57eff0fd1770e97d8c30fab # v1.0.1
    permissions:
      contents: write
      actions: read
    secrets: inherit
    with:
      channel: 4.11/edge
      integration-workflow-name: integration_test.yaml
