# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

name: Publish to edge

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish-to-edge:
    uses: canonical/charm-ci/.github/workflows/publish-artifacts.yml@14b1cf49d48b9d5b96192d9bca2890c98b7295cf # v1.0.2
    permissions:
      contents: write
      actions: read
    secrets: inherit
    with:
      channel: 4.14/edge
      integration-workflow-name: integration_test.yaml
